import { LocationId } from './constants';

export interface TransferRoute {
  slug: string;
  fromId: LocationId;
  toId: LocationId;
  fromLabel: string;
  toLabel: string;
  fromFull: string;
  toFull: string;
  prices: { eClass: number; vClass: number; sClass: number };
  distanceKm: number;
  durationMin: number;
  seoTitle: string;
  seoDescription: string;
  h1: string;
  h1Highlight: string;
  intro: string;
  features: string[];
  content: string[];
  relatedSlugs: string[];
}

export const TRANSFER_ROUTES: TransferRoute[] = [
  {
    slug: 'cdg-paris-transfer',
    fromId: 'cdg',
    toId: 'paris',
    fromLabel: 'CDG Airport',
    toLabel: 'Paris',
    fromFull: 'Charles de Gaulle Airport (CDG)',
    toFull: 'Paris City Center',
    prices: { eClass: 110, vClass: 130, sClass: 200 },
    distanceKm: 35,
    durationMin: 45,
    seoTitle: 'CDG Airport Transfer to Paris | Fixed Price from €110 | Paris Airports Transfers',
    seoDescription: 'Private chauffeur from Charles de Gaulle Airport (CDG) to Paris. Fixed rate from €110, meet & greet at arrivals, flight tracking, no hidden fees. Available 24/7.',
    h1: 'CDG Airport Transfer',
    h1Highlight: 'to Paris',
    intro: 'Private chauffeur from Charles de Gaulle Airport to any Paris address. Fixed price, no meter, no surge pricing — what you see is what you pay.',
    features: [
      'Meet & greet at arrivals hall with name board',
      'All CDG terminals covered (T1, T2A–F, T3)',
      'Flight tracking — driver waits free if your flight is delayed',
      'Child seats available on request',
      'Available 24/7, 365 days a year',
    ],
    content: [
      'Charles de Gaulle Airport (CDG) is located 35 km north-east of Paris, approximately 45 minutes by private car depending on traffic. A private transfer is the most stress-free option after a long-haul flight — no queues, no shared shuttles, your driver is waiting for you.',
      'Our fleet includes the Mercedes E-Class (up to 4 passengers), the Mercedes V-Class (up to 7 passengers), and the Mercedes S-Class for ultimate first-class comfort. All vehicles are air-conditioned and equipped with Wi-Fi on request.',
      'We cover all three CDG terminals: Terminal 1 (international arrivals), Terminal 2 (T2A, T2B, T2C, T2D, T2E, T2F — Air France hub), and Terminal 3 (low-cost carriers). Your chauffeur will meet you at the arrivals exit with your name on a board.',
    ],
    relatedSlugs: ['orly-paris-transfer', 'cdg-versailles-transfer', 'disneyland-paris-transfer'],
  },
  {
    slug: 'orly-paris-transfer',
    fromId: 'orly',
    toId: 'paris',
    fromLabel: 'Orly Airport',
    toLabel: 'Paris',
    fromFull: 'Orly Airport (ORY)',
    toFull: 'Paris City Center',
    prices: { eClass: 90, vClass: 100, sClass: 150 },
    distanceKm: 18,
    durationMin: 30,
    seoTitle: 'Orly Airport Transfer to Paris | Fixed Price from €90 | Paris Airports Transfers',
    seoDescription: 'Private chauffeur from Orly Airport (ORY) to Paris. Fixed rate from €90, meet & greet included, no hidden fees. Available 24/7. Book your Orly Paris transfer online.',
    h1: 'Orly Airport Transfer',
    h1Highlight: 'to Paris',
    intro: 'Private chauffeur from Orly Airport to any Paris address. The closest airport to Paris — just 18 km south. Fixed price, no surprises.',
    features: [
      'Meet & greet at Orly 1, 2, 3 or 4 terminals',
      'Flight tracking — driver waits free if delayed',
      'Fastest route to Paris city center',
      'Child seats available on request',
      'Available 24/7, 365 days a year',
    ],
    content: [
      'Orly Airport (ORY) is located 14 km south of Paris city center — the closest of the two main Paris airports. A private transfer from Orly to Paris takes approximately 25–40 minutes depending on traffic, typically faster than a CDG transfer.',
      'Orly has four terminals: Orly 1 (Orly Sud), Orly 2, Orly 3, and Orly 4 (Orly Ouest). Our driver will meet you at the arrivals exit of your terminal. Simply let us know your terminal when booking.',
      'Orly serves many European and domestic routes, as well as transatlantic flights. Whether arriving from New York, London, Madrid or Casablanca, your private Mercedes will be waiting at the arrivals hall.',
    ],
    relatedSlugs: ['cdg-paris-transfer', 'orly-versailles-transfer', 'orly-disneyland-transfer'],
  },
  {
    slug: 'le-bourget-paris-transfer',
    fromId: 'le_bourget',
    toId: 'paris',
    fromLabel: 'Le Bourget Airport',
    toLabel: 'Paris',
    fromFull: 'Le Bourget Airport (LBG)',
    toFull: 'Paris City Center',
    prices: { eClass: 110, vClass: 130, sClass: 200 },
    distanceKm: 15,
    durationMin: 30,
    seoTitle: 'Le Bourget Airport Transfer to Paris | Private Jet Transfer | From €110',
    seoDescription: 'Private chauffeur from Le Bourget Airport (LBG) to Paris. Dedicated service for private jet & charter arrivals. Fixed rate from €110, available 24/7.',
    h1: 'Le Bourget Airport Transfer',
    h1Highlight: 'to Paris',
    intro: 'Dedicated private transfer from Le Bourget Airport — the premier private aviation hub in Europe. Discreet, on-time, fixed price.',
    features: [
      'Dedicated service for private jet & charter arrivals',
      'On-tarmac or FBO meeting on request',
      'Le Bourget is 15 km from central Paris',
      'Mercedes S-Class available for VIP arrivals',
      'Available 24/7, 365 days a year',
    ],
    content: [
      'Le Bourget Airport (LBG), located 12 km north of Paris, is Europe\'s largest business aviation airport. It handles private jets, charter flights, and corporate aviation exclusively — there are no scheduled commercial flights.',
      'Arriving by private jet or charter? Your Mercedes chauffeur will be coordinating directly with the FBO or handling agent to ensure seamless pickup. Discreet, professional, and punctual.',
      'The journey from Le Bourget to central Paris takes approximately 25–35 minutes. For guests heading to luxury hotels in the 8th arrondissement or near the Champs-Élysées, Le Bourget is often the most convenient Paris airport.',
    ],
    relatedSlugs: ['cdg-paris-transfer', 'cdg-le-bourget-transfer', 'le-bourget-versailles-transfer'],
  },
  {
    slug: 'paris-versailles-transfer',
    fromId: 'paris',
    toId: 'versailles',
    fromLabel: 'Paris',
    toLabel: 'Versailles',
    fromFull: 'Paris City Center',
    toFull: 'Palace of Versailles',
    prices: { eClass: 110, vClass: 130, sClass: 200 },
    distanceKm: 22,
    durationMin: 35,
    seoTitle: 'Paris to Versailles Transfer | Private Chauffeur | Fixed Price €110',
    seoDescription: 'Private chauffeur from Paris to the Palace of Versailles. Fixed rate from €110, door-to-door service, no hidden fees. Perfect for day trips. Book online.',
    h1: 'Paris to Versailles',
    h1Highlight: 'Private Transfer',
    intro: 'Private chauffeur from Paris to the Palace of Versailles and back. The most comfortable way to visit one of France\'s most iconic monuments.',
    features: [
      'Door-to-door from your Paris hotel',
      'Drop-off at the Palace main entrance',
      'Return trip available — driver waits or comes back',
      'Avoid the RER crowds',
      'Available 7 days a week',
    ],
    content: [
      'The Palace of Versailles is one of the most visited monuments in the world, attracting over 10 million visitors per year. Located 22 km south-west of Paris, it is easily accessible by private car in 30–40 minutes.',
      'Unlike the RER C train, a private transfer drops you directly at the Palace entrance — no walking, no crowds, no connections. Your driver picks you up from your hotel door and takes you straight to the gates.',
      'We also offer return transfers. Your driver can wait for you (billed hourly) or pick you up at a scheduled time. Many guests combine their Versailles visit with a stop at the Gardens or the Trianons.',
    ],
    relatedSlugs: ['cdg-versailles-transfer', 'orly-versailles-transfer', 'paris-disneyland-transfer'],
  },
  {
    slug: 'paris-disneyland-transfer',
    fromId: 'paris',
    toId: 'disney',
    fromLabel: 'Paris',
    toLabel: 'Disneyland Paris',
    fromFull: 'Paris City Center',
    toFull: 'Disneyland Paris (Marne-la-Vallée)',
    prices: { eClass: 110, vClass: 130, sClass: 200 },
    distanceKm: 32,
    durationMin: 40,
    seoTitle: 'Paris to Disneyland Paris Transfer | Private Chauffeur | From €110',
    seoDescription: 'Private chauffeur from Paris to Disneyland Paris. Fixed rate from €110, child seats available, direct to your Disney hotel. Book online.',
    h1: 'Paris to Disneyland Paris',
    h1Highlight: 'Private Transfer',
    intro: 'Private chauffeur from central Paris directly to your Disneyland Paris hotel. No stress, no RER, child seats available on request.',
    features: [
      'Direct to your Disney hotel entrance',
      'Child seats and booster seats available',
      'Mercedes V-Class fits the whole family (up to 7)',
      'No connections, no luggage dragging',
      'Available 7 days a week',
    ],
    content: [
      'Disneyland Paris is located 32 km east of Paris in Marne-la-Vallée. While the RER A connects Paris to Disneyland, it requires connections and is not practical with young children and luggage.',
      'A private transfer takes you directly from your Paris hotel to the entrance of your Disney hotel — the whole family in one vehicle. Our Mercedes V-Class comfortably seats 7 passengers with luggage.',
      'Disneyland Paris has several on-site hotels (Hotel New York, Sequoia Lodge, Newport Bay Club, etc.) and nearby partner hotels. Just indicate your hotel at booking and your driver will take you directly there.',
    ],
    relatedSlugs: ['disneyland-paris-transfer', 'orly-disneyland-transfer', 'paris-versailles-transfer'],
  },
  {
    slug: 'disneyland-paris-transfer',
    fromId: 'cdg',
    toId: 'disney',
    fromLabel: 'CDG Airport',
    toLabel: 'Disneyland Paris',
    fromFull: 'Charles de Gaulle Airport (CDG)',
    toFull: 'Disneyland Paris (Marne-la-Vallée)',
    prices: { eClass: 110, vClass: 130, sClass: 200 },
    distanceKm: 45,
    durationMin: 40,
    seoTitle: 'CDG Airport to Disneyland Paris Transfer | Fixed Price €110 | Paris Airports Transfers',
    seoDescription: 'Private transfer from CDG Airport directly to Disneyland Paris. Fixed price from €110, child seats available, meet & greet at arrivals. Book online.',
    h1: 'CDG to Disneyland Paris',
    h1Highlight: 'Direct Transfer',
    intro: 'Skip Paris entirely. From Charles de Gaulle Airport straight to the magic of Disneyland Paris — one comfortable ride for the whole family.',
    features: [
      'Direct CDG → Disneyland Paris, no transit through Paris',
      'Child seats and booster seats available',
      'Meet & greet at CDG arrivals with name board',
      'Flight tracking — driver waits if delayed',
      'All CDG terminals covered',
    ],
    content: [
      'If Disneyland Paris is your final destination, there\'s no need to go through Paris. CDG Airport to Disneyland Paris is a direct 45-minute drive east, bypassing the city entirely.',
      'Our driver meets you at CDG arrivals, helps with luggage, and takes you directly to the entrance of your Disney hotel. Perfect for families arriving from North America, Asia, or the UK.',
      'The route runs along the A104 motorway and avoids Paris traffic. During peak season (school holidays, summer), this direct route saves you hours compared to public transport options.',
    ],
    relatedSlugs: ['cdg-paris-transfer', 'orly-disneyland-transfer', 'paris-disneyland-transfer'],
  },
  {
    slug: 'cdg-versailles-transfer',
    fromId: 'cdg',
    toId: 'versailles',
    fromLabel: 'CDG Airport',
    toLabel: 'Versailles',
    fromFull: 'Charles de Gaulle Airport (CDG)',
    toFull: 'Palace of Versailles',
    prices: { eClass: 140, vClass: 160, sClass: 220 },
    distanceKm: 55,
    durationMin: 60,
    seoTitle: 'CDG Airport to Versailles Transfer | Fixed Price from €140 | Paris Airports Transfers',
    seoDescription: 'Private chauffeur from CDG Airport directly to the Palace of Versailles. Fixed rate from €140, meet & greet, flight tracking. Book online.',
    h1: 'CDG Airport to Versailles',
    h1Highlight: 'Direct Transfer',
    intro: 'Arrive at CDG and go directly to Versailles — no Paris transit. Meet & greet at arrivals, straight to the Palace gates.',
    features: [
      'Direct CDG → Versailles, no Paris transit',
      'Meet & greet at CDG arrivals',
      'Flight tracking — driver waits if delayed',
      'Drop-off at Palace main entrance',
      'Return transfer available',
    ],
    content: [
      'Heading to Versailles from CDG without stopping in Paris? Our direct transfer takes you from Charles de Gaulle Airport to the Palace gates in approximately 55–70 minutes, depending on traffic.',
      'This route is popular with guests staying in Versailles or visiting as a first stop before heading to Paris. Many travelers arriving from the US or Asia combine CDG arrival with an immediate Versailles visit.',
      'The Palace of Versailles is best visited in the morning before the crowds arrive. A direct CDG transfer means you can be at the Palace gates within an hour of landing.',
    ],
    relatedSlugs: ['cdg-paris-transfer', 'orly-versailles-transfer', 'paris-versailles-transfer'],
  },
  {
    slug: 'cdg-orly-transfer',
    fromId: 'cdg',
    toId: 'orly',
    fromLabel: 'CDG Airport',
    toLabel: 'Orly Airport',
    fromFull: 'Charles de Gaulle Airport (CDG)',
    toFull: 'Orly Airport (ORY)',
    prices: { eClass: 120, vClass: 150, sClass: 180 },
    distanceKm: 55,
    durationMin: 55,
    seoTitle: 'CDG to Orly Airport Transfer | Inter-Airport | Fixed Price from €120',
    seoDescription: 'Private transfer between CDG and Orly airports. Fixed rate from €120, no public transport connections, direct door-to-door. Available 24/7.',
    h1: 'CDG to Orly',
    h1Highlight: 'Inter-Airport Transfer',
    intro: 'Private transfer between Charles de Gaulle and Orly airports. The simplest way to connect between Paris\'s two main airports — fixed price, direct route.',
    features: [
      'Direct CDG ↔ Orly, no public transport',
      'Flight tracking for connecting flights',
      'Luggage assistance included',
      'Fixed price — no meter running',
      'Available 24/7',
    ],
    content: [
      'Connecting between CDG and Orly? The two airports are 55 km apart. There is no direct public transport link — connecting via RER requires going into Paris and transferring, taking over 2 hours.',
      'A private transfer is the only sensible option for tight connections. The journey takes approximately 50–65 minutes by private car, directly from terminal to terminal.',
      'We coordinate pickup timing with your inbound flight. If your CDG flight is delayed, your driver is notified automatically and adjusts accordingly.',
    ],
    relatedSlugs: ['cdg-paris-transfer', 'orly-paris-transfer', 'orly-le-bourget-transfer'],
  },
  {
    slug: 'cdg-le-bourget-transfer',
    fromId: 'cdg',
    toId: 'le_bourget',
    fromLabel: 'CDG Airport',
    toLabel: 'Le Bourget Airport',
    fromFull: 'Charles de Gaulle Airport (CDG)',
    toFull: 'Le Bourget Airport (LBG)',
    prices: { eClass: 70, vClass: 80, sClass: 100 },
    distanceKm: 12,
    durationMin: 20,
    seoTitle: 'CDG to Le Bourget Airport Transfer | From €70 | Paris Airports Transfers',
    seoDescription: 'Private transfer from CDG Airport to Le Bourget Airport (private aviation). Fixed rate from €70. The two airports are just 12 km apart. Book online.',
    h1: 'CDG to Le Bourget',
    h1Highlight: 'Airport Transfer',
    intro: 'The two airports are just 12 km apart. Transfer between CDG commercial flights and Le Bourget private aviation — the shortest inter-airport route in Paris.',
    features: [
      'Just 12 km — approximately 20 minutes',
      'CDG commercial → Le Bourget private aviation',
      'Or reverse: Le Bourget → CDG departures',
      'Luggage assistance',
      'Available 24/7',
    ],
    content: [
      'CDG and Le Bourget are the two closest airports in the Paris area, just 12 km apart. This transfer is popular with corporate travelers who arrive at CDG on a commercial flight and continue on a private jet from Le Bourget — or vice versa.',
      'The journey takes approximately 15–25 minutes depending on traffic. Our driver meets you at CDG arrivals and takes you directly to your FBO or terminal at Le Bourget.',
      'At €70 for an E-Class, this is the most affordable inter-airport transfer in Paris — and the most efficient.',
    ],
    relatedSlugs: ['le-bourget-paris-transfer', 'cdg-paris-transfer', 'cdg-orly-transfer'],
  },
  {
    slug: 'orly-versailles-transfer',
    fromId: 'orly',
    toId: 'versailles',
    fromLabel: 'Orly Airport',
    toLabel: 'Versailles',
    fromFull: 'Orly Airport (ORY)',
    toFull: 'Palace of Versailles',
    prices: { eClass: 120, vClass: 150, sClass: 180 },
    distanceKm: 35,
    durationMin: 40,
    seoTitle: 'Orly Airport to Versailles Transfer | Fixed Price from €120 | Paris Airports Transfers',
    seoDescription: 'Private chauffeur from Orly Airport directly to the Palace of Versailles. Fixed rate from €120, meet & greet, no transit through Paris. Book online.',
    h1: 'Orly Airport to Versailles',
    h1Highlight: 'Direct Transfer',
    intro: 'From Orly Airport straight to the Palace of Versailles — no transit through Paris. Meet & greet at arrivals, direct to the Palace gates.',
    features: [
      'Direct Orly → Versailles, bypass Paris traffic',
      'Meet & greet at Orly terminals',
      'Flight tracking — driver waits if delayed',
      'Drop-off at Palace main entrance',
      'Return transfer available',
    ],
    content: [
      'Orly Airport is well-positioned for a direct transfer to Versailles — the two are connected by the A86 ring road, bypassing Paris entirely. The journey takes approximately 35–50 minutes.',
      'This route is ideal for travelers arriving from Southern Europe or North Africa who want to visit Versailles before checking into their Paris hotel.',
      'The Palace of Versailles receives over 10 million visitors annually. Arriving by private transfer means you go straight from the arrivals hall to the Palace entrance without any connections or luggage complications.',
    ],
    relatedSlugs: ['orly-paris-transfer', 'cdg-versailles-transfer', 'paris-versailles-transfer'],
  },
  {
    slug: 'orly-disneyland-transfer',
    fromId: 'orly',
    toId: 'disney',
    fromLabel: 'Orly Airport',
    toLabel: 'Disneyland Paris',
    fromFull: 'Orly Airport (ORY)',
    toFull: 'Disneyland Paris (Marne-la-Vallée)',
    prices: { eClass: 120, vClass: 150, sClass: 180 },
    distanceKm: 45,
    durationMin: 45,
    seoTitle: 'Orly Airport to Disneyland Paris Transfer | From €120 | Paris Airports Transfers',
    seoDescription: 'Private transfer from Orly Airport directly to Disneyland Paris. Fixed rate from €120, child seats available, meet & greet at arrivals. Book online.',
    h1: 'Orly Airport to Disneyland Paris',
    h1Highlight: 'Direct Transfer',
    intro: 'From Orly Airport straight to the magic of Disneyland Paris — one ride, no connections, child seats available for the family.',
    features: [
      'Direct Orly → Disneyland Paris',
      'Meet & greet at Orly arrivals',
      'Child seats and booster seats available',
      'Flight tracking — driver waits if delayed',
      'Mercedes V-Class for large families',
    ],
    content: [
      'Traveling with family from Orly to Disneyland Paris? The transfer takes approximately 40–55 minutes via the A86 and A4 motorways. No transit through Paris, no metro connections with luggage.',
      'Orly is a popular arrival airport for families coming from Spain, Italy, Portugal, and North Africa. A direct private transfer to Disneyland is far more practical than navigating public transport with children and strollers.',
      'Our Mercedes V-Class can accommodate up to 7 passengers with luggage, making it ideal for family groups. Child seats are available at no extra charge — just mention your children\'s ages at booking.',
    ],
    relatedSlugs: ['orly-paris-transfer', 'disneyland-paris-transfer', 'paris-disneyland-transfer'],
  },
  {
    slug: 'orly-le-bourget-transfer',
    fromId: 'orly',
    toId: 'le_bourget',
    fromLabel: 'Orly Airport',
    toLabel: 'Le Bourget Airport',
    fromFull: 'Orly Airport (ORY)',
    toFull: 'Le Bourget Airport (LBG)',
    prices: { eClass: 120, vClass: 150, sClass: 180 },
    distanceKm: 50,
    durationMin: 50,
    seoTitle: 'Orly to Le Bourget Airport Transfer | From €120 | Paris Airports Transfers',
    seoDescription: 'Private transfer from Orly Airport to Le Bourget (private aviation hub). Fixed rate from €120. Available 24/7. Book online.',
    h1: 'Orly to Le Bourget',
    h1Highlight: 'Inter-Airport Transfer',
    intro: 'Connect from Orly commercial flights to Le Bourget private aviation — or the reverse. Fixed price, direct route, no public transport connections.',
    features: [
      'Direct Orly ↔ Le Bourget',
      'For commercial-to-private aviation connections',
      'Luggage assistance',
      'Fixed price — no meter running',
      'Available 24/7',
    ],
    content: [
      'Orly and Le Bourget are on opposite sides of Paris, connected by the A86 ring road. The journey takes approximately 45–60 minutes by private car.',
      'This transfer is popular with executives who arrive on commercial flights at Orly and continue on a private charter or corporate jet from Le Bourget, or vice versa.',
      'There is no direct public transport between these two airports. A private transfer is the only practical option for this connection.',
    ],
    relatedSlugs: ['orly-paris-transfer', 'le-bourget-paris-transfer', 'cdg-orly-transfer'],
  },
  {
    slug: 'le-bourget-versailles-transfer',
    fromId: 'le_bourget',
    toId: 'versailles',
    fromLabel: 'Le Bourget Airport',
    toLabel: 'Versailles',
    fromFull: 'Le Bourget Airport (LBG)',
    toFull: 'Palace of Versailles',
    prices: { eClass: 140, vClass: 160, sClass: 220 },
    distanceKm: 45,
    durationMin: 50,
    seoTitle: 'Le Bourget to Versailles Transfer | Private Jet to Palace | From €140',
    seoDescription: 'Private chauffeur from Le Bourget Airport directly to the Palace of Versailles. Fixed rate from €140. Discreet VIP service. Book online.',
    h1: 'Le Bourget to Versailles',
    h1Highlight: 'Direct Transfer',
    intro: 'Step off your private jet at Le Bourget and arrive at the Palace of Versailles — the ultimate arrival experience in France.',
    features: [
      'Direct Le Bourget → Palace of Versailles',
      'Discreet VIP service',
      'Mercedes S-Class available',
      'On-tarmac coordination with FBO',
      'Available 24/7',
    ],
    content: [
      'Le Bourget to Versailles is one of the most prestigious transfer routes in France. Arriving by private jet and heading directly to the Palace — bypassing Paris entirely — is the ultimate luxury travel experience.',
      'The journey takes approximately 45–60 minutes via the A86 and N12. Our chauffeur coordinates with your FBO or handling agent at Le Bourget to ensure seamless pickup.',
      'The Palace of Versailles is also available for private evening events. If you are attending a private dinner or event at the Château, our S-Class Mercedes provides the appropriate arrival.',
    ],
    relatedSlugs: ['le-bourget-paris-transfer', 'cdg-versailles-transfer', 'paris-versailles-transfer'],
  },
  {
    slug: 'le-bourget-disneyland-transfer',
    fromId: 'le_bourget',
    toId: 'disney',
    fromLabel: 'Le Bourget Airport',
    toLabel: 'Disneyland Paris',
    fromFull: 'Le Bourget Airport (LBG)',
    toFull: 'Disneyland Paris (Marne-la-Vallée)',
    prices: { eClass: 110, vClass: 130, sClass: 200 },
    distanceKm: 40,
    durationMin: 40,
    seoTitle: 'Le Bourget to Disneyland Paris Transfer | From €110 | Paris Airports Transfers',
    seoDescription: 'Private transfer from Le Bourget Airport directly to Disneyland Paris. Fixed rate from €110. Child seats available. Book online.',
    h1: 'Le Bourget to Disneyland Paris',
    h1Highlight: 'Private Transfer',
    intro: 'From Le Bourget private aviation directly to Disneyland Paris — perfect for families arriving by private charter.',
    features: [
      'Direct Le Bourget → Disneyland Paris',
      'Child seats available',
      'Mercedes V-Class for families',
      'On-tarmac coordination available',
      'Available 24/7',
    ],
    content: [
      'Arriving by private jet or charter at Le Bourget with the family? Disneyland Paris is just 40 km east — a straight 35–50 minute drive without going through Paris.',
      'This route runs via the A104 motorway, one of the most direct connections between Le Bourget and Disneyland. Our V-Class can accommodate the whole family with luggage.',
      'From tarmac to Disney hotel entrance — we handle the rest so the magic starts the moment you land.',
    ],
    relatedSlugs: ['le-bourget-paris-transfer', 'disneyland-paris-transfer', 'orly-disneyland-transfer'],
  },
  {
    slug: 'versailles-disneyland-transfer',
    fromId: 'versailles',
    toId: 'disney',
    fromLabel: 'Versailles',
    toLabel: 'Disneyland Paris',
    fromFull: 'Palace of Versailles',
    toFull: 'Disneyland Paris (Marne-la-Vallée)',
    prices: { eClass: 140, vClass: 160, sClass: 220 },
    distanceKm: 55,
    durationMin: 55,
    seoTitle: 'Versailles to Disneyland Paris Transfer | From €140 | Paris Airports Transfers',
    seoDescription: 'Private transfer from the Palace of Versailles to Disneyland Paris. Fixed rate from €140, no transit through Paris, direct route. Book online.',
    h1: 'Versailles to Disneyland Paris',
    h1Highlight: 'Private Transfer',
    intro: 'From the Palace of Versailles to Disneyland Paris in one comfortable ride — the perfect combination for a family trip to France.',
    features: [
      'Direct Versailles → Disneyland Paris',
      'No transit through Paris',
      'Child seats available',
      'Flexible pickup from Palace area or hotel',
      'Available 7 days a week',
    ],
    content: [
      'Versailles and Disneyland Paris are both located outside Paris, on roughly opposite sides of the city. A direct transfer connects the two without going through central Paris, taking approximately 50–65 minutes via the A86 ring road.',
      'Many families visiting France combine these two iconic destinations — the grandeur of the Palace of Versailles and the excitement of Disneyland. A private transfer makes the connection seamless.',
      'We can pick you up from the Palace of Versailles, from your Versailles hotel, or from any address in the area.',
    ],
    relatedSlugs: ['paris-versailles-transfer', 'paris-disneyland-transfer', 'cdg-versailles-transfer'],
  },
];

export function getRouteBySlug(slug: string): TransferRoute | undefined {
  return TRANSFER_ROUTES.find(r => r.slug === slug);
}
